apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  ports:
  - protocol: TCP
    port: 80        # Puerto expuesto dentro del clúster
    targetPort: 80  # Puerto al que se redirige dentro de los pods de Drupal
    nodePort: 30080 # Puerto que puedes usar para acceder desde fuera del clúster
  type: NodePort